# Generated by Django 4.1.7 on 2023-03-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_medicina_creado_el_medicina_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='doctores'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes'),
        ),
    ]
